name = "roviq-station"
main = "src/index.js"
compatibility_date = "2024-11-01"

kv_namespaces = [
  { binding = "CONTENT", id = "0a3a91e8fa63462eae8cf3f2e77e8a22" }
]

# Set with: wrangler secret put ADMIN_PASSWORD
# Set with: wrangler secret put SESSION_SECRET
